baseURL = "https://blog.chvatal.com"
title = "Jacob Chvatal"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Jacob Chvatal's blog."
  copyright = "Copyright © 2020 Jacob Chvatal"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "https://jacob.chvatal.com"
    weight = 20

[permalinks]
  posts = "/:title/"

[footer]
  [[footer.main]]
    identifier = "cc"
    name = "cc"
    path = ""
    url = ""
  [[footer.main]]
    identifier = "webring"
    name = "webring"
    path = ""
    url = ""

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
